Dev
reloadedd/UniversalStorageTool pull request #3
Opened 2021-04-07 10:50 UTC by iulianPeiu6

Partea dreapta a paginii account a fost creata, continand o statistica a spatiului ocupat de fiecare drive si un buton prin care utilizatorul poate adauga un nou drive. Va rog verificati! <3

2021-04-09 06:17 UTC, reloadedd commented
Nu ii pot da merge, ai conflicte.

![image](https://user-images.githubusercontent.com/24204354/114137163-72d6af80-9914-11eb-92a0-6e754de0f5c2.png)

2021-04-09 19:27 UTC, TacheRadu requested changes

2021-04-09 19:27 UTC, TacheRadu commented on app/views/account.html
> +    <link rel="stylesheet" href="../../public/css/account.css">
scoate ../../

2021-04-09 19:27 UTC, TacheRadu commented on app/views/account.html
> +        <img class="avatar-img" src="../../public/img/avatar.png" title="Profile avatar" alt="">
scoate ../../

2021-04-09 19:27 UTC, TacheRadu commented on app/views/account.html
> +        <img class="statistics-img" src="../../public/img/statistics.png" title="Statistics icon" alt="">
scoate ../../

2021-04-09 19:27 UTC, TacheRadu commented on app/views/user_entry.html
> +    <link rel="stylesheet" href="../../public/css/user_entry.css">
scoate ../../

2021-04-09 19:27 UTC, TacheRadu commented on app/views/user_entry.html
> +        <img src="../../public/img/logo.png" class="logo" alt="logo image">
scoate ../../

2021-04-09 19:27 UTC, TacheRadu commented on public/css/account.css
> +    background-color: rgba(0,0,0,0.9);
Which one is it?

2021-04-09 19:27 UTC, TacheRadu commented on public/css/account.css
> +    background-color: rgba(0,0,0,0.9);
Once again, which one is it?

2021-04-09 19:27 UTC, TacheRadu commented on public/css/account.css
> +    border: 1px solid rgba(0,0,0,0.3);
Or here?

2021-04-10 05:35 UTC, TacheRadu approved these changes

2021-04-10 07:50 UTC, TacheRadu approved these changes

2021-04-10 07:51 UTC, reloadedd approved these changes

2021-04-10 07:52 UTC, merged